{"text": "In deploying model part, I wanted to test my model locally on a test-image data and I had this silly error after the following command:\nurl = 'https://github.com/bhasarma/kitchenware-classification-project/blob/main/test-image.jpg'\nX = preprocessor.from_url(url)\nI got the error:\nUnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f797010a590>\nSolution:\nAdd ?raw=true after .jpg in url. E.g. as below\nurl = \u2018https://github.com/bhasarma/kitchenware-classification-project/blob/main/test-image.jpg?raw=true\u2019\nBhaskar Sarma", "section": "Miscellaneous", "question": "Error UnidentifiedImageError: cannot identify image file", "course": "machine-learning-zoomcamp", "document_id": "4603e4e5"}