{"text": "To solve this error mention the location = US when creating the dim_zones table\n{{ config(\nmaterialized='table',\nlocation='US'\n) }}\nJust Update this part to solve the issue and run the dim_zones again and then run the fact_trips", "section": "error: Error while reading table: trips_data_all.external_fhv_tripdata, error message: Parquet column 'DOlocationID' has type INT64 which does not match the target cpp_type DOUBLE.", "question": "Dim_zones.sql Dataset was not found in location US When Running fact_trips.sql", "course": "data-engineering-zoomcamp", "document_id": "c65d8fd9"}