{"text": "Problem description:   Running starter.ipynb in homework\u2019s Q1 will show up this error.\nSolution description: Update pandas (actually pandas version was the latest, but several dependencies are updated).\nAdded by Marcos Jimenez", "section": "Module 4: Deployment", "question": "Error index 311297 is out of bounds for axis 0 with size 131483 when loading parquet file.", "course": "mlops-zoomcamp", "document_id": "7a6f23eb"}